### ISSUE TITLE
`vpdetection.exe` is an empty executable.

### ISSUE THREAD

**Issue by RezaBehzadpour** [SunskyF/StructCompletion-python#2]
When testing the project for new images, `vpdetection.exe` can not create vanishing points for the new images, because `vpdetection.exe` is an empty executable with the size of 0.

The following error will arise when you use the empty `vpdetection.exe` file to create the vanishing points for the new image:
```python
Traceback (most recent call last):
  File "demo.py", line 17, in <module>
    img, mask, maskD, modelPlane, modelReg = extract_planar_structure(image_name, optA)
  File "E:\python\git\StructCompletion-python\source\extract\extract_planar_structure.py", line 34, in extract_planar_structure
    modelPlane = extract_plane(image_name, image, maskD, option)
  File "E:\python\git\StructCompletion-python\source\extract\extract_plane.py", line 266, in extract_plane
    vpData = read_vpdata(os.path.join(vpFilePath, 'text', vpFileName))
  File "E:\python\git\StructCompletion-python\source\extract\extract_plane.py", line 217, in read_vpdata
    with open(fileName, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cache/vpdetection\\text\\015_input_hole-vanishingpoints.txt'
```

**Comment by SunskyF** [comment]
Thanks!
